# Generated by Django 4.2.3 on 2023-07-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
